version: '2'
services:
 docker-springboot-sample:
  build:
   context: .
   dockerfile: Dockerfile
   args:
    - APP_JAR=target/docker-spring-boot-0.0.1-SNAPSHOT.jar
  ports:
   - "8080:8080"
  networks:
   - docker-springboot-network
  image: docker-springboot-sample:first
  container_name: docker-springboot-sample
 mypostgresql:
  image: postgres:9.4.18-alpine
  ports:
   - "5432:5432"
  volumes:
   - ./init.sql:/docker-entrypoint-initdb.d/1-schema.sql
  environment:
   - POSTGRES_USER:'postgres'
   - POSTGRES_PASSWORD:'password'
   - POSTGRES_DB:'postgres'
  networks:
   - docker-springboot-network
networks:
 docker-springboot-network:
  driver: bridge

